"""add_hearings_fees_collected_fees_due

Revision ID: 474e8c0bebce
Revises: 722eefae49a1
Create Date: 2026-06-18 15:39:25.818797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474e8c0bebce'
down_revision: Union[str, Sequence[str], None] = '722eefae49a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees_collected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash', 'bank_transfer', 'cheque', 'upi', 'other', name='paymentmode'), nullable=False),
    sa.Column('reference_number', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fees_collected', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fees_collected_id'), ['id'], unique=False)

    op.create_table('fees_due',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.Enum('retainer', 'appearance', 'consultation', 'documentation', 'misc', name='feetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fees_due', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fees_due_id'), ['id'], unique=False)

    op.create_table('hearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=False),
    sa.Column('court_name', sa.String(length=300), nullable=False),
    sa.Column('judge_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'adjourned', 'cancelled', name='hearingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hearings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hearings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hearings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hearings_id'))

    op.drop_table('hearings')
    with op.batch_alter_table('fees_due', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fees_due_id'))

    op.drop_table('fees_due')
    with op.batch_alter_table('fees_collected', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fees_collected_id'))

    op.drop_table('fees_collected')
    # ### end Alembic commands ###
