"""add_scheduled_job_runs

Revision ID: 81665ba86789
Revises: ea94773ec007
Create Date: 2026-07-21 17:37:22.693973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81665ba86789'
down_revision: Union[str, Sequence[str], None] = 'ea94773ec007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('slot_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('worker', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'slot_key', name='uq_job_slot')
    )
    with op.batch_alter_table('scheduled_job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_job_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_job_runs_job_id'), ['job_id'], unique=False)
    # NOTE: autogenerate also flagged a pre-existing misuse_reports.created_at nullability drift
    # (model NOT NULL vs head nullable). Left out of THIS migration — it is unrelated to Phase 3
    # and altering to NOT NULL needs a data check first. Tracked as a separate follow-up.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_job_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_job_runs_id'))

    op.drop_table('scheduled_job_runs')
    # ### end Alembic commands ###
