"""add_court_diary_tables

Revision ID: ebb3145426f3
Revises: 474e8c0bebce
Create Date: 2026-06-18 15:45:56.133897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb3145426f3'
down_revision: Union[str, Sequence[str], None] = '474e8c0bebce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=False),
    sa.Column('hearing_time', sa.Time(), nullable=True),
    sa.Column('court_name', sa.String(length=300), nullable=False),
    sa.Column('court_room', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('first_hearing', 'arguments', 'final_arguments', 'judgment', 'other', name='hearingstage'), nullable=False),
    sa.Column('outcome', sa.Enum('pending', 'heard', 'adjourned', 'part_heard', 'decided', name='hearingoutcome'), nullable=False),
    sa.Column('adjournment_reason', sa.String(length=500), nullable=True),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_entries_id'), ['id'], unique=False)

    op.create_table('diary_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diary_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_tasks_id'), ['id'], unique=False)

    op.create_table('filing_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('is_filed', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filing_deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_deadlines_id'), ['id'], unique=False)

    op.create_table('opposing_counsel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('advocate_name', sa.String(length=200), nullable=False),
    sa.Column('bar_registration_number', sa.String(length=100), nullable=True),
    sa.Column('firm_name', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opposing_counsel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opposing_counsel_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opposing_counsel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opposing_counsel_id'))

    op.drop_table('opposing_counsel')
    with op.batch_alter_table('filing_deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_deadlines_id'))

    op.drop_table('filing_deadlines')
    with op.batch_alter_table('diary_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_tasks_id'))

    op.drop_table('diary_tasks')
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_entries_id'))

    op.drop_table('diary_entries')
    # ### end Alembic commands ###
